#
#  Makefile for the kernel Sensor device drivers.
#

obj-$(CONFIG_SENSORS_CORE_P5LTE)		+= sensors_core.o
obj-$(CONFIG_GYRO_K3G_P5LTE)			+= k3g.o
obj-$(CONFIG_SENSORS_AK8975_P5LTE)	+= ak8975.o
obj-$(CONFIG_SENSORS_K3DH_P5LTE)		+= k3dh.o
obj-$(CONFIG_OPTICAL_BH1721_P5LTE)	+=bh1721.o
