# drivers/media/video/samsung/mhl_v1/Makefile
#
# Copyright (c) 2010 Samsung Electronics Co., Ltd.
# 		http://www.samsung.com/
# Aakash Manik
#	aakash.manik@samsung.com



obj-$(CONFIG_VIDEO_MHL_V1) += sii9234.o \
				si_RegioCbus.o \
				SiI9234_I2C_master.o \
				sii9234_driver.o \
				si_apiCbus.o \
				si_cpCbus.o 

